[binaries]
c = 'arm-none-eabi-gcc'
cpp = 'arm-none-eabi-g++'
ar = 'arm-none-eabi-ar'
ld = 'arm-none-eabi-g++'
objcopy = 'arm-none-eabi-objcopy'
strip = 'arm-none-eabi-strip'

# host machine - the machine on which the compiled binary will run
[host_machine]
system = 'none'
kernel = 'none'
cpu_family = 'arm'
cpu = 'cortex-a9'
endian = 'little'